// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ScopeBuddy

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image1;
void ui_event_ButtonON(lv_event_t * e);
lv_obj_t * ui_ButtonON;
lv_obj_t * ui_LabelON;
void ui_event_ButtonOFF(lv_event_t * e);
lv_obj_t * ui_ButtonOFF;
lv_obj_t * ui_LabelOFF;
lv_obj_t * ui_FrequencySlider;
lv_obj_t * ui_FrequencyValue;
lv_obj_t * ui_DutySlider;
lv_obj_t * ui_DutyValue;
lv_obj_t * ui_StatusLabel;
lv_obj_t * ui_RandomButton;
lv_obj_t * ui_RandomLabel;
lv_obj_t * ui_RevealButton;
lv_obj_t * ui_RevealLabel;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonON(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        LedOn(e);
    }
}

void ui_event_ButtonOFF(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        LedOff(e);
    }
}

void ui_event_FrequencySlider(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED) WaveFrequencyChanged(e);
}

void ui_event_DutySlider(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED) WaveDutyChanged(e);
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
