// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ScopeBuddy

#ifndef _SCOPEBUDDY_UI_H
#define _SCOPEBUDDY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
void ui_event_ButtonON(lv_event_t * e);
extern lv_obj_t * ui_ButtonON;
extern lv_obj_t * ui_LabelON;
void ui_event_ButtonOFF(lv_event_t * e);
extern lv_obj_t * ui_ButtonOFF;
extern lv_obj_t * ui_LabelOFF;
extern lv_obj_t * ui_FrequencySlider;
extern lv_obj_t * ui_FrequencyValue;
extern lv_obj_t * ui_DutySlider;
extern lv_obj_t * ui_DutyValue;
extern lv_obj_t * ui_StatusLabel;
extern lv_obj_t * ui_RandomButton;
extern lv_obj_t * ui_RandomLabel;
extern lv_obj_t * ui_RevealButton;
extern lv_obj_t * ui_RevealLabel;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_scopebuddy_logo);       // assets/scopebuddy_logo_30x52.png
LV_IMG_DECLARE(ui_img_scopebuddy_splash);     // assets/scopebuddy_logo_splash_80x139.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
