// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Aiuto-Vista (fork of ScopeBuddy, https://github.com/johannesboernsen/ScopeBuddy)

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void LedOn(lv_event_t * e);
void LedOff(lv_event_t * e);
void WaveFrequencyChanged(lv_event_t * e);
void WaveDutyChanged(lv_event_t * e);
void WaveRandomChallenge(lv_event_t * e);
void WaveRevealChallenge(lv_event_t * e);
void WaveUiInit(void);
void WaveHardwareReady(bool ready);
void GameUiBuildStart(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
